### ISSUE TITLE
addDeviceOrientationListener not working on IOS device when Auto-rotate turn off

### ISSUE THREAD

**Issue by dinhtrumdieu** [wonday/react-native-orientation-locker#141]
I want to listen to orientation changes when the AUTO rotate turn off. The fact that I wasn't getting addDeviceOrientationListener on IOS even when it was working on Android

**Comment by liran** [comment]
+1, Is there a solution?

**Comment by psamd** [comment]
+1

**Comment by Cannonball2134** [comment]
Any update on this? I have it working on Android but the same code doesn't work on IOS (Testing on an Iphone 11).

**Comment by jzxchiang1** [comment]
Having the same exact issue...

**Comment by jzxchiang1** [comment]
Resolved it by patching this on my local `react-native-orientation-locker` package:

https://gist.github.com/jzxchiang1/bd7e906038eb9a2c57857b5f1a0d6a3f

Use `npx patch-package` to do that.

Code copied from `react-native-camera`, which implements this correctly: https://github.com/react-native-camera/react-native-camera/blob/941536592cb8ad6f65f3cb50e2fe814b7c70c093/ios/RCT/RCTSensorOrientationChecker.m

Hope this helps!

**Comment by chungvqvinorsoft** [comment]
Unfortunately I'm using react-native-orientation-lock 1.6, and after running npx patch-package and npm run ios it still doesn't work even though the above process doesn't error.

**Comment by eliasg52** [comment]
I have the same problem, auto rotate works on android but not on ios

**Comment by CyxouD** [comment]
Not fixed in 1.7.0

**Comment by CyxouD** [comment]
@jzxchiang1  It doesn't work in my case (I use 1.5 version, but it shouldn't matter)
